# Generated by Django 2.1 on 2018-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='lastname',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='shipping_destination',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15),
        ),
    ]
