# Generated by Django 2.1 on 2018-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20181109_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='shipping',
            new_name='is_credit_card',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='shipping_destination',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='annual_income',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='card_list',
            field=models.CharField(blank=True, choices=[('hdfc', 'HDFC'), ('icici', 'ICICI'), ('other', 'Other')], max_length=15),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='occupation_type',
            field=models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self-employed business', 'Self-Employed Business'), ('self-employed professional', 'Self-Employed Professional')], max_length=15),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='pincode',
            field=models.IntegerField(default=False),
        ),
    ]
