# Generated by Django 2.1 on 2018-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20181109_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageLocation', models.CharField(max_length=100)),
                ('is_Travel', models.BooleanField(default=False)),
                ('is_Airport_Lounge', models.BooleanField(default=False)),
                ('is_Shopping', models.BooleanField(default=False)),
                ('is_Dining', models.BooleanField(default=False)),
                ('is_Movies', models.BooleanField(default=False)),
                ('is_Fuel', models.BooleanField(default=False)),
                ('first_year_fees', models.IntegerField(default=False)),
                ('reward_values', models.IntegerField(default=False)),
                ('chance_of_Approval', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
