# Generated by Django 2.1 on 2018-11-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_offerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerinfo',
            name='offerName',
            field=models.CharField(default='Offer', max_length=100),
        ),
    ]
