# Generated by Django 2.1 on 2018-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_offerinfo_offername'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_type', models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self-employed business', 'Self-Employed Business'), ('self-employed professional', 'Self-Employed Professional')], max_length=15)),
                ('annual_income', models.IntegerField(default=False)),
                ('pincode', models.IntegerField(default=False)),
                ('email', models.CharField(max_length=100)),
                ('offer_id', models.IntegerField(default=False)),
            ],
        ),
    ]
