# Generated by Django 2.1 on 2018-11-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_bookedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedinfo',
            name='company_name',
            field=models.CharField(blank=True, choices=[('interra', 'Interra'), ('test_IT', 'Test Company'), ('digital_company', 'Digital Company')], max_length=15),
        ),
        migrations.AddField(
            model_name='bookedinfo',
            name='firstName',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='bookedinfo',
            name='mobile',
            field=models.IntegerField(default=False),
        ),
    ]
